In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread('./img/house.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [3]:
# SIFT 추출기 생성
sift = cv2.xfeatures2d.SIFT_create()

# 키 포인트 검출과 디스크립터 계산
keypoints, descriptor = sift.detectAndCompute(gray, None)

In [4]:
print('keypoint:', len(keypoints), 'descriptor:', descriptor.shape)
print(descriptor)

keypoint: 413 descriptor: (413, 128)
[[  1.   1.   1. ...   0.   0.   1.]
 [  8.  24.   0. ...   1.   0.   4.]
 [  0.   0.   0. ...   0.   0.   2.]
 ...
 [  1.   8.  71. ...  73. 127.   3.]
 [ 35.   2.   7. ...   0.   0.   9.]
 [ 36.  34.   3. ...   0.   0.   1.]]


In [5]:
# 키 포인트 그리기
img_draw = cv2.drawKeypoints(img, keypoints, None, 
                            flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

In [6]:
# 결과 출력
cv2.imshow('SIFT', img_draw)
cv2.waitKey()
cv2.destroyAllWindows()